name: ReActions
main: me.fromgate.reactions.ReActions
version: 0.6.1/8    
website: http://fromgate.me
author: fromgate, fromgate@gmail.com
softdepend: [Vault,Towny,WorldGuard,RacesAndClasses,PlayEffect,Factions,Craftconomy3]
commands:
   react:
      aliases: [ra,rea,rct]
      description: 
      usage: 
           /react help